alias srcbash='source ~/.bashrc'
alias ls='ls -l'
alias gcc='gcc-4.9'
alias ctags_update='ctags -a -R --excmd=n --exclude=arm --exclude=mechanical --exclude=firmware/libraries'
alias ctags_new='ctags -R --excmd=n --exclude=mechanical'
alias vim='mvim -v'
alias gdb='arm-none-eabi-gdb'
alias grepstr='grep -Irnw . -e'
alias robo='cd ~/Documents/Github/roborodentia2017/firmware'
alias venv_tensor='source ~/tensorflow/bin/activate'
